baseURL = "https://vesper.netlify.app/"
languageCode = "en-us"
summaryLength = 25
title = "My New Hugo Site"
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
parent = "Resources"
url = "/blog"
weight = 3
[[menu.main]]
name = "Home Value Request"
parent = "Sellers"
url = "/home-valuation"
weight = 1
[[menu.main]]
name = "Resources"
weight = 4
[[menu.main]]
name = "Sellers"
weight = 3
[[menu.main]]
name = "Buyers"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload/"
[taxonomies]
category = "categories"
city = "cities"
featured = "featured"
property = "properties"
state = "states"
status = "status"
tag = "tags"
zip = "zip-codes"